server:
  port: 8084

spring:
  application:
    name: vacation-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/staffsync_vacation}
    username: ${DB_USER:staffsync}
    password: ${DB_PASS:staffsync}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
